import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Toaster } from 'sonner';
import './globals.css';
import { Topbar } from '@/components/topbar';
import { ReactQueryProvider } from '@/providers/react-query';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <Toaster
        duration={3000}
        position='bottom-center'
        toastOptions={{
          classNames: {
            success: 'bg-green-500 text-white border-green-700',
            error: 'bg-destructive text-white border-destructive',
          },
        }}
      />
      <body className={inter.className}>
        <ReactQueryProvider>
          <>
            <Topbar />
            {children}
          </>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
